###
#  This a SubMakefile of the principal Makefile.
#
# clean 	: delete all the file that end with "~"
#
# Author	:dmike
# Email		:cipmiky@gmail.com
#
##

PHONY = clean

clean: 
	$(RM) *~ *.aux

.PHONY : PHONY